services:
  ansible:
    build: ./ansible_controller
    user: root
    container_name: ansible_controller
    volumes:
      - ./ansible_controller:/ansible
    command: ["python", "controller_worker.py"]
    working_dir: /ansible
    depends_on:
      - tailscale
    network_mode: "service:tailscale"
    env_file:
      - .env
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
    - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env
    restart: unless-stopped

  node_tracker: # not scalable at the moment
    build: ./node_tracker
    container_name: node_tracker
    env_file:
      - .env
    volumes:
      - ./node_tracker/node_tracker.py:/node_tracker.py
    working_dir: /
    command: ["python", "node_tracker.py"]
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  tailscale_data:
  rabbitmq_data:  