version: "3.8"

services:
  ansible:
    build: .
    network_mode: "host"
    container_name: ansible-controller
    volumes:
      - ../ansible_server_files:/ansible
    entrypoint: /bin/bash -c "chmod 600 /ansible/ssh_private_key && python ansible_broadcast_listener.py"
    working_dir: /ansible
    tty: true