services:
  ansible:
    build: .
    user: root
    container_name: ansible-controller
    volumes:
      - ../ansible_server_files:/ansible
    entrypoint: ["/bin/bash", "-c", "chmod 600 /ansible/ansible_ssh_key && tail -f /dev/null"]
    working_dir: /ansible
    network_mode: "service:tailscale"
    tty: true

  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ../ansible_server_files/tailscale:/var/lib/tailscale
    working_dir: /ansible
    tty: true