- name: Install Softwares on Windows
  hosts: all
  gather_facts: True
  tasks:
    # Create a file to indicate Ansible has started setup
    - name: Append connection log entry
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Ansible Controller Connected, Starting setup"

    # Create edge shortcut with custom URL on desktop for all users
    - name: Create Microsoft Edge shortcut on desktop with custom URL
      ansible.windows.win_copy:
        dest: C:\Users\Public\Desktop\Microsoft Edge.url
        content: |
          [InternetShortcut]
          URL=https://deanza.edu
          IconFile=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
          IconIndex=0

    - name: Append log entry for shortcut creation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Created new URL shortcut"

    # Install multiple packages with Chocolatey
    - name: Install multiple packages
      win_chocolatey:
        name:
        - libreoffice
        - zoom
        - vlc
        - firefox
        state: present

    - name: Append log entry for package installation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Installed packages: LibreOffice, Zoom, VLC, Firefox"

    # Configure Firefox homepage and install uBlock Origin extension via policies.json
    - name: Create Firefox policies folder
      win_file:
        path: C:\Program Files\Mozilla Firefox\distribution
        state: directory

    - name: Set Firefox homepage via policies.json
      win_copy:
        dest: C:\Program Files\Mozilla Firefox\distribution\policies.json
        content: |
          {
            "policies": {
              "Homepage": {
                "URL": "https://www.deanza.edu",
                "Locked": false
              },
              "Preferences": {
                "browser.startup.page": 1,
                "browser.startup.homepage": "https://www.deanza.edu"
              },
              "Extensions": {
                "Install": [
                  "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
                ]
              }
            }
          }

    - name: Append log entry for Firefox homepage configuration
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Set Firefox homepage and installed uBlock Origin extension"

    # Create scheduled task to set default browser to firefox
    - name: Apply LibreOffice default save format for each user
      win_copy:
        src: set_default_browser_script.ps1
        dest: C:\Windows\CompTechS\set_default_browser_script.ps1

    - name: Run default browser script in user session
      community.windows.win_scheduled_task:
        name: SetDefaultBrowser
        actions:
          - path: powershell.exe
            arguments: -ExecutionPolicy Bypass -File C:\Windows\CompTechS\set_default_browser_script.ps1
        triggers:
          - type: logon
        username: Student
        run_level: highest
        state: present

    - name: Append log entry for scheduled task creation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Created scheduled task to set default browser at next logon"

    # Run the scheduled task immediately in the user session to set the default browser without waiting for the next logon
    - name: Run task immediately in user session
      ansible.windows.win_shell: |
        schtasks /run /tn "SetDefaultBrowser"

    - name: Append log entry for scheduled task execution
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Ran scheduled task to set default browser"

    # Delete the scheduled task after execution to clean up
    - name: Delete scheduled task via PowerShell
      ansible.windows.win_shell: |
        Unregister-ScheduledTask -TaskName "SetDefaultBrowser" -Confirm:$false

    - name: Append log entry for scheduled task deletion
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Deleted scheduled task to set default browser"


    # Configure LibreOffice default save format to ms office by copying registrymodifications.xcu to each user's LibreOffice profile folder
    - name: Ensure destination folder exists on Windows
      ansible.windows.win_file:
        path: C:\Users\Student\AppData\Roaming\LibreOffice\4\user
        state: directory

    - name: Apply LibreOffice default save format for each user
      win_copy:
        src: libreoffice_registrymodifications.xcu
        dest: C:\Users\Student\AppData\Roaming\LibreOffice\4\user\registrymodifications.xcu

    - name: Append log entry for LibreOffice default save format configuration
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Configured LibreOffice default save format"

    # Install drivers from windows update using PSWindowsUpdate module
    - name: Copy PSWindowsUpdate installation script to Windows
      win_copy:
        src: install_psupdate_script.ps1
        dest: C:\Windows\CompTechS\install_psupdate_script.ps1

    - name: Run PSWindowsUpdate script in user session
      community.windows.win_scheduled_task:
        name: InstallPSWindowsUpdate
        actions:
          - path: powershell.exe
            arguments: -ExecutionPolicy Bypass -File C:\Windows\CompTechS\install_psupdate_script.ps1
        triggers:
          - type: logon
        username: Student
        run_level: highest
        state: present

    - name: Append log entry for scheduled task creation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Created scheduled task to install driver updates at next logon"

    # Run the scheduled task immediately in the user session to set the default browser without waiting for the next logon
    - name: Run task immediately in user session
      ansible.windows.win_shell: |
        schtasks /run /tn "InstallPSWindowsUpdate"

    - name: Append log entry for scheduled task execution
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Ran scheduled task to install driver updates"

    # Delete the scheduled task after execution to clean up
    - name: Delete scheduled task via PowerShell
      ansible.windows.win_shell: |
        Unregister-ScheduledTask -TaskName "InstallPSWindowsUpdate" -Confirm:$false

    - name: Append log entry for scheduled task deletion
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Deleted scheduled task to install driver updates"

    # Install drivers from windows update using PSWindowsUpdate module with SYSTEM privileges to ensure all drivers get installed without user context limitations
    - name: Run Windows Update task as SYSTEM
      community.windows.win_scheduled_task:
        name: DriverUpdateJob
        actions:
          - path: powershell.exe
            arguments: |
              -ExecutionPolicy Bypass -Command "Import-Module PSWindowsUpdate; Get-WindowsUpdate -MicrosoftUpdate -Category Drivers -AcceptAll -Install"
        username: SYSTEM
        run_level: highest
        triggers:
        - type: logon
        state: present

    - name: Execute task
      ansible.windows.win_shell: 
        schtasks /run /tn DriverUpdateJob

    - name: Delete scheduled task via PowerShell
      ansible.windows.win_shell: |
        Unregister-ScheduledTask -TaskName "DriverUpdateJob" -Confirm:$false

    - name: Append log entry for driver installation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Running driver updates"

    # Create a scheduled task to run the debloat script with admin privileges at next logon, then run it immediately in the SYSTEM context to ensure it executes without user context limitations and applies debloat changes successfully
    - name: Run Windows Update task as SYSTEM
      community.windows.win_scheduled_task:
        name: "RunDebloatAdmin"
        actions:
          - path: powershell.exe
            arguments: -ExecutionPolicy Bypass -File C:\Windows\CompTechS\Win11Debloat\Win11Debloat.ps1 -RunDefaults -Silent
        username: Student
        run_level: highest
        triggers:
        - type: logon
        state: present

    - name: Run scheduled task immediately
      ansible.windows.win_shell: schtasks /run /TN "RunDebloatAdmin"

    - name: Delete scheduled task via PowerShell
      ansible.windows.win_shell: |
        Unregister-ScheduledTask -TaskName "RunDebloatAdmin" -Confirm:$false
        
    - name: Append log entry for debloat script execution
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Running debloat script"

    # End of playbook, add a pause to allow any pending operations to complete before Ansible disconnects
    - name: Wait for system stabilization
      ansible.builtin.pause:
        minutes: 3

    - name: Append log entry for debloat script execution
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] Playbook almost completed, waiting for system stabilization before removing Tailscale and OpenSSH. ***IMPORTANT: Please look for removal logs of Tailscale and OpenSSH in this file to confirm they were uninstalled successfully. If you do not see those logs within 10 minutes, please check if Tailscale and OpenSSH are still installed and uninstall them manually if needed.***"

    # remove tailscale and openssh server, check if it's really uninstalled
    - name: Copy final uninstallation script to Windows
      win_copy:
        src: uninstall_openssh_tailscale.ps1
        dest: C:\Windows\CompTechS\uninstall_openssh_tailscale.ps1

    - name: Append log entry for uninstallation script creation
      community.windows.win_lineinfile:
        path: C:\Windows\CompTechS\log.txt
        create: true
        line: "[{{ ansible_facts.date_time.date }} {{ ansible_facts.date_time.time }}] End of playbook reached, copied uninstallation script to Windows, now running it in user session to remove Tailscale and OpenSSH."
        insertafter: EOF

    - name: Run uninstallation script in user session
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\Windows\CompTechS\uninstall_openssh_tailscale.ps1

    
