name: Windows Tailscale Test

on:
  workflow_dispatch:

jobs:
  tailscale:
    runs-on: windows-latest

    steps:
      - name: Download source code
        uses: actions/checkout@v4

      # Install Tailscale
      - name: Install Tailscale
        shell: powershell
        run: |
          choco install tailscale -y

      - name: Run Tailscale directly
        shell: powershell
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" version

      # Refresh environment
      - name: Add Tailscale to current PATH
        shell: powershell
        run: |
          $tailscalePath = "C:\Program Files\Tailscale"
          $env:Path = "$env:Path;$tailscalePath"
          tailscale version

      # Start Tailscale service
      - name: Start Tailscale
        shell: powershell
        run: |
          Start-Service Tailscale

      # Authenticate with auth key
      - name: Connect to Tailscale
        shell: powershell
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY_CLIENT }}
        run: |
          tailscale up --authkey $env:TS_AUTHKEY --hostname github-win-runner-client

      # Verify connection
      - name: Check status
        shell: powershell
        run: |
          tailscale status
          tailscale ip
