name: Windows Tailscale Test

on:
  workflow_dispatch:

jobs:
  client:
    runs-on: windows-latest

    environment: dev

    steps:
      - name: Download source code
        uses: actions/checkout@v4

      # Install Tailscale
      - name: Install Tailscale
        shell: powershell
        run: |
          choco install tailscale -y

      - name: Run Tailscale directly
        shell: powershell
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" version

      # Refresh environment
      - name: Add Tailscale to PATH
        shell: powershell
        run: |
          echo "C:\Program Files\Tailscale" >> $env:GITHUB_PATH

      # Start Tailscale service
      - name: Start Tailscale
        shell: powershell
        run: |
          Start-Service Tailscale

      # Authenticate with auth key
      - name: Connect to Tailscale
        shell: powershell
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY_CLIENT }}
        run: |
          tailscale up --authkey $env:TS_AUTHKEY --hostname github-win-runner-client

      # Verify connection
      - name: Check status
        shell: powershell
        run: |
          tailscale status
          tailscale ip

  server:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Download source code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY_SERVER }}

      - name: Test connection
        run: |
          tailscale ip
          tailscale status
